### ISSUE TITLE
ModDivisonDataset

### ISSUE THREAD

**Issue by garyhlai** [Sea-Snell/grokking#1]
Why do you have `(a * pow(b, self.p-2, self.p)) % self.p` for ModDivisonDataset? Shouldn't it be `(a / b) % self.p`?

**Comment by Sea-Snell** [comment]
the one you are proposing does not compute the modular inverse correctly; in fact it can return floating point values (if using python3). See [here](https://mathworld.wolfram.com/ModularInverse.html) or [here](https://en.wikipedia.org/wiki/Division_ring) to see how my formula works.
