### ISSUE TITLE
Default weight_decay is 0

### ISSUE THREAD

**Issue by sytelus** [Sea-Snell/grokking#4]
According to paper, the `weight_decay` should be 1. However, your config has it as 0. Is this correct? I am trying to reproduce Figure 1 and I thought that must have been produced with `weight_Decay=1` per appendix A.1.2.

**Comment by Sea-Snell** [comment]
Sorry for the really late reply; I just noticed this issue. To Answer your question, towards the end of appendix A.1.2 it states:
```
For the experiments reported in Section 3.1 we increased the optimization budget to 106, and used Adam optimizer with no weight decay, for emphasizing how late into the optimization process the generalization can begin.
```

So Figure 1 was actually produced with weight_decay=0.0.
